### ISSUE TITLE
JSON serialization always includes Visual Paradigm's default datatype

### ISSUE THREAD

**Issue by tgoprince** [OntoUML/ontouml-vp-plugin#72] opened 2020-09-29 07:36 UTC
Whenever we serialize a model in JSON (compliant with ontouml-schema), we include all Visual Paradigm's default dataypes, namely: 

- boolean
- byte
- char
- double
- float
- int
- long
- short
- string
- void

This happens regardless if a model actually uses these datatypes or not.

I think the plugin should only serialize them if they are referenced by an attribute.

**Comment by matheuslenke** [comment] 2024-05-27 14:21
Hey Tiago,
I couldn't reproduce this issue. After doing some research in the code, I found that i was already fixed by @claudenirmf with the following lines of code at `IProjectTransformer.java` with the `getUsedDatatypes` method.
<img width="1010" alt="image" src="https://github.com/OntoUML/ontouml-vp-plugin/assets/50427349/c8bbc25e-7507-4040-8cac-8d38f6bd9e41">

**Closed by matheuslenke** 2024-05-27 14:21 UTC
Labels: bug
