### ISSUE TITLE
Plugin error while using n-ary association

### ISSUE THREAD

**Issue by jcctesolin** [OntoUML/ontouml-vp-plugin#132] opened 2022-03-15 20:49 UTC
![image](https://user-images.githubusercontent.com/86018252/158468540-d1f672a0-1a06-4165-9619-d04a7dd406f3.png)

Hi,

I am testing a ternary relation but I am getting a plugin error while checking the model. Can you check it ?
Visual Paradigm v16.3 OntoUML plugin v 0.5.3 . VP project attached

Thanks in advance

Julio Tesolin

[test4.vpp.zip](https://github.com/OntoUML/ontouml-vp-plugin/files/8256986/test4.vpp.zip)

**Comment by claudenirmf** [comment] 2022-03-16 09:48
Hi, @jcctesolin! Thank you for your feedback. At the moment, we have an issue on the serialization of n-ray associations that prevents the usage of verification and transformation features. This won't prevent you from using all features, for example, the stereotype menus and automatic coloring still work normally. Nonetheless we should soon be publishing a fix for this bug.

For the moment I'll be closing your commit because it is a duplicate of #114, but feel free to join the discussion there too.

**Closed by claudenirmf** 2022-03-16 09:48 UTC
